# Generated by Django 5.1.2 on 2025-01-09 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_share', '0002_alter_usercredentials_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContacts',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('first', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first', to=settings.AUTH_USER_MODEL)),
                ('second', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDevices',
            fields=[
                ('device_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('identifier', models.TextField()),
                ('os', models.TextField(choices=[('ios', 'ios'), ('android', 'android'), ('windows', 'windows'), ('macos', 'macos')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SharedDocuments',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('data', models.JSONField()),
                ('time', models.TextField()),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second', to='file_share.userdevices')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first', to='file_share.userdevices')),
            ],
        ),
    ]
