# Generated by Django 5.1.2 on 2025-01-10 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_share', '0004_alter_userdevices_os'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdevices',
            old_name='os',
            new_name='platform',
        ),
    ]
