# Generated by Django 5.1.2 on 2025-01-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_share', '0005_rename_os_userdevices_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdevices',
            name='name',
            field=models.TextField(default='dummy'),
            preserve_default=False,
        ),
    ]
