# Generated by Django 5.1.2 on 2025-01-12 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_share', '0007_usercontacts_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shareddocuments',
            name='receiver',
        ),
        migrations.AddField(
            model_name='shareddocuments',
            name='receiver_contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_contact', to='file_share.usercontacts'),
        ),
        migrations.AddField(
            model_name='shareddocuments',
            name='receiver_device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_device', to='file_share.userdevices'),
        ),
        migrations.AlterField(
            model_name='shareddocuments',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='file_share.userdevices'),
        ),
    ]
