# Generated by Django 5.1.2 on 2025-01-13 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_share', '0008_remove_shareddocuments_receiver_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shareddocuments',
            old_name='receiver_contact',
            new_name='recipient_contact',
        ),
        migrations.RenameField(
            model_name='shareddocuments',
            old_name='receiver_device',
            new_name='recipient_device',
        ),
    ]
