# Generated by Django 5.1.2 on 2025-01-13 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_share', '0009_rename_receiver_contact_shareddocuments_recipient_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareddocuments',
            name='time',
            field=models.TimeField(),
        ),
    ]
