# Generated by Django 5.1.2 on 2025-01-13 05:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_share', '0010_alter_shareddocuments_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shareddocuments',
            name='time',
        ),
        migrations.AddField(
            model_name='shareddocuments',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 13, 10, 46, 7, 962966)),
            preserve_default=False,
        ),
    ]
