# Generated by Django 5.1.2 on 2025-01-13 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_share', '0011_remove_shareddocuments_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercredentials',
            name='time',
        ),
        migrations.AddField(
            model_name='usercredentials',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
