# Generated by Django 5.1.2 on 2025-01-13 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_share', '0012_remove_usercredentials_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareddocuments',
            name='recipient_contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_contact', to=settings.AUTH_USER_MODEL),
        ),
    ]
