# Generated by Django 5.1.2 on 2025-01-13 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_share', '0013_alter_shareddocuments_recipient_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shareddocuments',
            name='sender',
        ),
        migrations.AddField(
            model_name='shareddocuments',
            name='sender_contact',
            field=models.ForeignKey(default=16, on_delete=django.db.models.deletion.CASCADE, related_name='sender_contact', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shareddocuments',
            name='sender_device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sender_device', to='file_share.userdevices'),
            preserve_default=False,
        ),
    ]
