# Generated by Django 5.1.2 on 2025-01-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_share', '0014_remove_shareddocuments_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareddocuments',
            name='opened',
            field=models.BooleanField(default=False),
        ),
    ]
